export enum AppActionTypes {
  SWITCH_THEME = 'SWITCH_THEME',
  APP_READY = 'APP_READY',
  ADD_TOAST = 'ADD_TOAST',
  REMOVE_TOAST = 'REMOVE_TOAST',
}

export enum JobActionTypes {
  SET_ACTIVE_JOB_CREATE_STEP = 'SET_ACTIVE_JOB_CREATE_STEP',
  CHANGE_CURRENT_SMALL_BAR_CHART_VALUE = 'CHANGE_CURRENT_SMALL_BAR_CHART_VALUE',
  LOAD_JOB_CREATE_DATA = 'LOAD_JOB_CREATE_DATA',
  CHOSE_JOB_DATA = 'CHOSE_JOB_DATA',
  REMOVE_FROM_CHOSEN_JOB_DATA = 'REMOVE_FROM_CHOSEN_JOB_DATA',
}
