export enum AppActionTypes {
  SWITCH_THEME = 'SWITCH_THEME',
  APP_READY = 'APP_READY',
}

export enum JobActionTypes {
  SET_ACTIVE_JOB_CREATE_STEP = 'SET_ACTIVE_JOB_CREATE_STEP',
  CHANGE_CURRENT_SMALL_BAR_CHART_VALUE = 'CHANGE_CURRENT_SMALL_BAR_CHART_VALUE',
  LOAD_JOB_CREATE_DATA = 'LOAD_JOB_CREATE_DATA',
}
